create database Empresa

create table TABLAS_DEPARTAMENTOS
(
DEPTNO char(3) not null,
DEPTNAME varchar(36) not null,
MGRNO char(6),
ADMRDEPT char(3) not null,
LOCATION char(16)
);

ALTER TABLE TABLAS_DEPARTAMENTOS ADD CONSTRAINT PK_TABLAS_DEPARTAMENTOS PRIMARY KEY CLUSTERED (DEPTNO);

create table TABLAS_EMPLEADOS
(
EMPNO char(6) not null,
FIRSTNME varchar(12) not null,
MIDINIT char(1) not null,
LASTNAME varchar(15) not null,
WORKDEPT char(3) not null,
PHONENO char(4) not null,
HIREDATE datetime not null,
JOB varchar(10) not null,
EDLEVEL smallint not null,
SEX char(1) not null,
BIRTHDATE date not null,
SALARY decimal(9,2) not null,
BONUS decimal(9,2)  not null
);

ALTER TABLE TABLAS_EMPLEADOS ADD CONSTRAINT PK_TABLAS_EMPLEADOS PRIMARY KEY CLUSTERED (EMPNO);


INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('A00','Sistemas', '000010','A10','')

use Empresa

INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('B01','Inventario', '000020','A00','')

Select * from TABLAS_DEPARTAMENTOS

INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('C01','Compras', '000030','A00','')

INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('D01','Mercadeo', '','A00','')

INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('D11','Administracion', '000060','D01','')

INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('D21','Soporte', '000050','D01','')

INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('E01','Servicio al cliente', '000040','A00','')

INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('F22','Oficina 1', '000090','E01','')

INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('F35','Calculos', '000080','C02','')

INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('G22','Oficina 2', '000070','E01','')

INSERT INTO TABLAS_DEPARTAMENTOS ("DEPTNO", "DEPTNAME", "MGRNO", "ADMRDEPT", "LOCATION")
VALUES('','', '','','')


INSERT INTO TABLAS_EMPLEADOS ("EMPNO", "FIRSTNME", "MIDINIT", "LASTNAME", "WORKDEPT", "PHONENO", "HIREDATE", "JOB", "EDLEVEL", "SEX", "BIRTHDATE", "SALARY", "BONUS")
VALUES ('000010', 'Jose', 'S', 'Sanchez', 'A00', '4125', '2010-05-17', 'sales', '15', 'F', '1979-05-10', '52648.99', '56892.62')

INSERT INTO TABLAS_EMPLEADOS ("EMPNO", "FIRSTNME", "MIDINIT", "LASTNAME", "WORKDEPT", "PHONENO", "HIREDATE", "JOB", "EDLEVEL", "SEX", "BIRTHDATE", "SALARY", "BONUS")
VALUES ('000020', 'Carmen', 'H', 'Vergara', 'B01', '4785', '2015-05-12', 'service', '10', 'M', '1980-08-05', '5624.66', '57482.12')

INSERT INTO TABLAS_EMPLEADOS ("EMPNO", "FIRSTNME", "MIDINIT", "LASTNAME", "WORKDEPT", "PHONENO", "HIREDATE", "JOB", "EDLEVEL", "SEX", "BIRTHDATE", "SALARY", "BONUS")
VALUES ('000030', 'Jorge', 'V', 'Venegas', 'D01', '4126', '2013-05-06', 'sales', '14', 'M', '1985-12-29', '4527.52', '4125.00')

INSERT INTO TABLAS_EMPLEADOS ("EMPNO", "FIRSTNME", "MIDINIT", "LASTNAME", "WORKDEPT", "PHONENO", "HIREDATE", "JOB", "EDLEVEL", "SEX", "BIRTHDATE", "SALARY", "BONUS")
VALUES ('000040', 'Mariana', 'T', 'Tadeo', 'D11', '4424', '2013-07-15', 'manager', '11', 'F', '1998-01-02', '599.00', '675.00')

INSERT INTO TABLAS_EMPLEADOS ("EMPNO", "FIRSTNME", "MIDINIT", "LASTNAME", "WORKDEPT", "PHONENO", "HIREDATE", "JOB", "EDLEVEL", "SEX", "BIRTHDATE", "SALARY", "BONUS")
VALUES ('000050', 'Jorge', 'R', 'Rodeo', 'D21', '4128', '2000-08-27', 'designer', '11', 'M', '1998-10-31', '795.00', '1500.00')


INSERT INTO TABLAS_EMPLEADOS ("EMPNO", "FIRSTNME", "MIDINIT", "LASTNAME", "WORKDEPT", "PHONENO", "HIREDATE", "JOB", "EDLEVEL", "SEX", "BIRTHDATE", "SALARY", "BONUS")
VALUES ('000060', 'Martha', 'V', 'Candenado', 'E01', '4129', '2005-09-14', 'designer', '16', 'F', '2002-12-09', '5000.00', '50.00')

Select * from TABLAS_EMPLEADOS

